#!/bin/bash

if [ $# != 1 ];then
    echo "Usage:$0 project name"
    exit
else
    pro_name=$1
fi

script_dir=$(dirname $0)

mkdir $pro_name
cd $pro_name
mkdir 'src'

cp $script_dir/Makefile .
sed -i "s/TARGET = XXX/TARGET = $pro_name/" ./Makefile

make build

exit
